services:
  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  courses-service:
    build:
      context: ./apps/courses-service
      dockerfile: Dockerfile
    depends_on:
      - courses-db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@courses-db:5432/courses-db?schemas=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  enrollments-service:
    build:
      context: ./apps/enrollments-service
      dockerfile: Dockerfile
    depends_on:
      - enrollments-db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@enrollments-db:5432/enrollments-db?schemas=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  students-service:
    build:
      context: ./apps/students-service
      dockerfile: Dockerfile
    depends_on:
      - students-db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@students-db:5432/students-db?schemas=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  courses-db:
    image: postgres:13
    environment:
      POSTGRES_DB: courses-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - courses-db-data:/var/lib/postgresql/data

  enrollments-db:
    image: postgres:13
    environment:
      POSTGRES_DB: enrollments-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - enrollments-db-data:/var/lib/postgresql/data

  students-db:
    image: postgres:13
    environment:
      POSTGRES_DB: students-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - students-db-data:/var/lib/postgresql/data

volumes:
  courses-db-data:
  enrollments-db-data:
  students-db-data: